### ISSUE TITLE
Can't time-travel into the future

### ISSUE THREAD

**Issue by kernelmethod** [apccurtiss/TIMESCRIPT#1]
# Steps to reproduce
`test.js`

```
var x = 1;
console.log(x@-1);
x = 2;
```

Running TIMESCRIPT:

```
$ node timescript.js test.ts
UnaryExpression {
  type: 'UnaryExpression',
  operator: '-',
  argument: Literal { type: 'Literal', value: 1, raw: '1' },
  prefix: true }
/home/will/Desktop/test/TIMESCRIPT/timescript.js:66
    throw Error(
    ^

Error: UnaryExpression is an unimplemented langugage feature. Don't be surprised, most of the language is unimplemented.
    at compile (/home/will/Desktop/test/TIMESCRIPT/timescript.js:66:11)
    at compile (/home/will/Desktop/test/TIMESCRIPT/timescript.js:37:65)
    at Array.map (<anonymous>)
    at compile (/home/will/Desktop/test/TIMESCRIPT/timescript.js:45:58)
    at compile (/home/will/Desktop/test/TIMESCRIPT/timescript.js:42:16)
    at Array.map (<anonymous>)
    at compile (/home/will/Desktop/test/TIMESCRIPT/timescript.js:10:26)
    at main (/home/will/Desktop/test/TIMESCRIPT/timescript.js:78:27)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

![tardis](https://user-images.githubusercontent.com/17100608/71339133-d4042500-250f-11ea-87c8-fa0708e364b4.gif)

**Comment by apccurtiss** [comment]
The language currently does not support Futures. Those are functional programming tools and functional programming requires immutability, which we can all degree is stupid temporalist garbage. The spec committee may one day agree to it if lobbied hard enough.
